# Generated by Django 5.1.5 on 2025-02-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_orig', models.CharField(max_length=64)),
                ('title_cz', models.CharField(blank=True, max_length=64, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('released_year', models.IntegerField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='viewer.genre')),
            ],
            options={
                'ordering': ['title_orig'],
            },
        ),
    ]
