# Generated by Django 5.1.5 on 2025-02-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_country_movie_created_movie_updated_movie_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
    ]
