# Generated by Django 5.1.5 on 2025-02-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_creator_movie_actors_movie_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
